version: '2'
services:
    expertsystem-app:
        image: expertsystem
        external_links:
            - expertsystem-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/expertsystem?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    expertsystem-mysql:
        extends:
            file: mysql.yml
            service: expertsystem-mysql
